drop table if exists account CASCADE;
drop table if exists transfer CASCADE;
drop table if exists user CASCADE;

create table account
(
    id      integer generated by default as identity,
    number  integer not null,
    user_id integer not null,
    primary key (id)
);
create table transfer
(
    id                   integer generated by default as identity,
    amount               double       not null,
    currency             varchar(255) not null,
    date                 timestamp    not null,
    description          varchar(255) not null,
    recipient_account_id integer      not null,
    sender_account_id    integer      not null,
    primary key (id)
);
create table user
(
    id       integer generated by default as identity,
    name     varchar(255) not null,
    password varchar(255) not null,
    username varchar(255) not null,
    primary key (id),
    unique (username)
);